language: swift

osx_image: xcode10.2

script:
  - xcodebuild -scheme SortingSimulator -sdk macosx -destination 'platform=macOS' build -derivedDataPath build

before_deploy:
  - sudo sntp -sS time.apple.com
  - security create-keychain -p mysecretpassword build.keychain
  - security default-keychain -s build.keychain
  - security unlock-keychain -p mysecretpassword build.keychain
  - security import pibox-installer.p12 -k build.keychain -P $MACOS_CERTIFICATE_PASSWORD -A
  - "security set-key-partition-list -S apple-tool:,apple: -s -k mysecretpassword build.keychain"
  - security find-identity -v
  - "codesign --force --sign \"Developer ID Application: sdy36071@naver.com (DSNGPFPWXA)\" \"build/Build/Products/Debug/SortingSimulator.app\" --deep"
  - cd build/Build/Products/Debug
  - npm install --global create-dmg
  - create-dmg SortingSimulator.app
  - mv SortingSimulator*.dmg ../../../../SortingSimulator.dmg
  - cd ../../../../

deploy:
  provider: releases

  api_key:
    secure: EfepK65BulKK20xooRosmpvliH+RHHZgKJ/JPHnCMLBnarepRlQpx2vvAoDykWHWehGVVH1FnBJD8M4wXhRhcLAGvMxX6/IyNt54xsxjCXSuDivdOzbA6QKHsfIFf5ubxy//X7cK1zWgdwerC+pSnMl5N7+YOvmpywpvQwRZzNDCPYEsYev/qJnBCBQjJe3uAWEhGrUWji9AZpCOf1cm6lUbB5gs8NzHimbYwwK+ZIk3VmxPvG5OSAcoTMq7PWwztCzwsXPebQ5CTA7S+JGJTvu2kydjDJXFiGO/AxhVwcYkCQpX7fLRWPIg0cCmlRSxksG68VRouMK0IiPCMuCy1fY9duQNSMwqBseQLU4zEMk5+MLjlkT2eVPOqGm/b94jjos9zh9EXRLpFq3JXuNslPF5xK2hXisgNm3RcHix5DYsVwW6x/SKfvl7cNa6OBJ1UYj3U1ZUpEYkO+zzceTIFrWVu7TwV5Sw4keLOJSh4+ijPB/1c4nsaVLZHA+LwOqi7lTp8qmPKa5jL8qLzL/4r6dQzgKvBa1e+2P39cCchJtsaZAMJEkyZkQHm4cXJIg5SblhLxISiRhx6Tx5ZLDyTW/92UswG4kFauFRaT7g7600PVM6Mb8VZLTUWVCSxUvNW+7pz9nI9YWN1QE8nW7qKHqP/TxDisbuS3V5mXVThJ0=

  file_glob: true
  file: SortingSimulator.dmg
  skip_cleanup: true

  on:
    tags: true
    all_branches: true
    repo: OrigamiDream/SortingSimulator
